import type { DocumentExtractionMetadata } from './document-extraction-metadata.js';
/** Portable record shapes. PostgreSQL compatibility is checked by records.test.ts.
 * These types are owned by persistence: change them intentionally, not on every SQL migration. */
import type { KnowledgeGraphAssertion } from './knowledge-graph-sync.js';

export interface Records {
  selfRepairIssues: {
    id: string;
    agentId: string;
    fingerprint: string;
    status: string;
    version: number;
    data: unknown;
    createdAt: Date;
    updatedAt: Date;
  };
  maintenanceCursors: {
    name: string;
    cursor: string | null;
    updatedAt: Date;
  };
  situationPacks: {
    id: string;
    data: unknown;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    creationKey: string;
    title: string;
    version: number;
    archived: boolean;
  };
  situationPreviews: {
    id: string;
    data: unknown;
    createdAt: Date;
    packId: string;
    baseVersion: number;
    sourceHash: string;
    status: string;
    expiresAt: Date;
  };
  agents: {
    id: string;
    name: string;
    email: string;
    calendarId: string | null;
    phoneE164: string | null;
    avatarUrl: string | null;
    signature: string;
    timezone: string;
    locale: string;
    workspacePrefix: string;
    browserProfilePath: string | null;
    credentialRefs: unknown;
    createdAt: Date;
    updatedAt: Date;
  };
  /** One outbound phone call the assistant placed for the owner. */
  callSessions: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    taskId: string;
    /** The tool_calls row the task is parked on until the call ends. */
    toolCallId: string;
    /** dialing | ringing | in_progress | completed | no_answer | busy | failed | canceled */
    status: string;
    to: string;
    contactName: string | null;
    /** The approved brief: goal, context, mayAgreeTo, mustNot, language, onVoicemail. */
    brief: unknown;
    voiceModel: string;
    /** Frozen provider/model/endpoint/rates snapshot; null means legacy or invalid. */
    voiceRoute: unknown | null;
    /** Frozen telephony line rate used by this call's reservation. */
    lineRate: unknown;
    maxMinutes: number;
    twilioCallSid: string | null;
    /** sha256 of the one-shot media-stream token; null once the stream has connected. */
    streamTokenHash: string | null;
    /** Raw job-callback token that wakes the parked task when the call ends. */
    callbackToken: string;
    reservationId: string | null;
    /** human | machine | unknown, from answering-machine detection. */
    answeredBy: string | null;
    startedAt: Date | null;
    endedAt: Date | null;
    durationSeconds: number | null;
    /** [{ role: 'caller' | 'assistant' | 'system', text, at }] */
    transcript: unknown;
    /** Ordered transcript append cursor and durable out-of-order batch receipts. */
    transcriptState: unknown;
    /** Facts the assistant noted during the call. */
    notes: unknown;
    /** [{ id, question, askedAt, answer, answeredAt, via }] */
    checkins: unknown;
    hangupRequested: boolean;
    outcome: string | null;
    summary: string | null;
    costUsd: string | null;
    error: string | null;
    /** Durable terminal result and metering work, replayed independently of call completion. */
    finishDelivery: unknown;
    capacityReleasedAt: Date | null;
  };
  mcpConnections: {
    id: string;
    name: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    endpoint: string;
    bearerTokenEncrypted: string | null;
    enabled: boolean;
    serverName: string | null;
    serverVersion: string | null;
    instructions: string | null;
    tools: unknown;
    lastCheckedAt: Date | null;
    lastError: string | null;
  };
  goals: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    title: string;
    status: string;
    description: string;
    priority: number;
    progress: string;
    nextAction: string;
    targetDate: Date | null;
    mirrorToPrimary: boolean;
    taintedOrigin: boolean;
    autonomy: boolean;
    archivedAt: Date | null;
  };
  conversations: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    title: string;
    archivedAt: Date | null;
    channel: string;
    trust: string;
    modelOverride: string | null;
    isPrimary: boolean;
    metadata: unknown;
    lastReadAt: Date | null;
    messageSequence: number;
  };
  channelBindings: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    channel: string;
    conversationId: string;
    externalId: string;
  };
  messages: {
    id: string;
    createdAt: Date;
    conversationId: string;
    taskId: string | null;
    role: string;
    parts: unknown;
    text: string;
    origin: string;
    channelMessageId: string | null;
    clientId: string | null;
    clientDeliveredAt: Date | null;
    clientDeliveredBy: string | null;
    embedding: number[] | null;
    embeddingSpaceKey: string | null;
    hiddenAt: Date | null;
    appendSequence: string;
  };
  generatedCards: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    expiresAt: Date | null;
    conversationId: string | null;
    messageId: string | null;
    sourceLabel: string;
    sourceFingerprint: string;
    currentRevisionId: string;
    dismissedAt: Date | null;
  };
  generatedCardRevisions: {
    id: string;
    createdAt: Date;
    version: number;
    cardId: string;
    spec: unknown;
  };
  commitments: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    title: string;
    status: string;
    nextAction: string;
    conversationId: string;
    sourceMessageId: string | null;
    sourceTaskId: string | null;
    /** Stable owner evidence identity retained after closure to prevent replay. */
    sourceOccurrenceKey: string | null;
    /** A manual owner reopen is a new occurrence linked to the closed source row. */
    reopenedFromId: string | null;
    reopenOperationId: string | null;
    kind: string;
    details: string;
    dueAt: Date | null;
    snoozedUntil: Date | null;
    resolvedAt: Date | null;
    resolution: string | null;
    confidence: string;
    contentHash: string;
  };
  conversationSegments: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    conversationId: string;
    embedding: number[] | null;
    embeddingSpaceKey: string | null;
    startMessageId: string;
    endMessageId: string;
    summary: string;
    messageCount: number;
    startedAt: Date;
    endedAt: Date;
  };
  tasks: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    title: string | null;
    status: string;
    progress: string;
    nextAction: string;
    archivedAt: Date | null;
    trust: string;
    conversationId: string | null;
    type: string;
    goalId: string | null;
    autonomyGrant: unknown;
    trigger: unknown;
    externalEventId: string | null;
    plan: unknown;
    state: unknown;
    progressPercent: number | null;
    deadline: Date | null;
    reflectEvery: string | null;
    lastReflectedAt: Date | null;
    runAfter: Date | null;
    lockedUntil: Date | null;
    leaseToken: string | null;
    queueGeneration: number;
    attempt: number;
    reclaimCount: number;
    maxSteps: number;
    budgetUsdLimit: string;
    spentUsd: string;
    parentTaskId: string | null;
    attentionNotifiedAt: Date | null;
  };
  missionReports: {
    id: string;
    agentId: string;
    missionId: string;
    goalId: string | null;
    conversationId: string | null;
    outcome: string;
    text: string;
    chatStatus: 'pending' | 'delivered' | 'skipped' | 'failed';
    ownerStatus: 'pending' | 'delivered' | 'skipped' | 'failed' | 'unknown';
    mirrorStatus: 'pending' | 'delivered' | 'skipped' | 'failed';
    claimToken: string | null;
    lockedUntil: Date | null;
    nextAttemptAt: Date;
    attempts: number;
    createdAt: Date;
    updatedAt: Date;
    chatDeliveredAt: Date | null;
    ownerDeliveredAt: Date | null;
    mirrorDeliveredAt: Date | null;
    lastError: string | null;
  };
  toolCalls: {
    id: string;
    createdAt: Date;
    status: string;
    taskId: string;
    startedAt: Date | null;
    step: number;
    toolName: string;
    args: unknown;
    risk: string;
    idempotencyKey: string | null;
    result: unknown;
    error: string | null;
    approvalId: string | null;
    decision: unknown;
    finishedAt: Date | null;
  };
  toolCallReceipts: {
    id: string;
    agentId: string;
    taskId: string;
    toolCallId: string;
    modelToolCallIdHash: string | null;
    idempotencyKeyHash: string | null;
    toolName: string;
    effectOutcome: import('./tool-call-receipts.js').ToolCallEffectOutcome;
    recordedAt: Date;
  };
  toolCallReceiptKeys: {
    id: string;
    agentId: string;
    taskId: string;
    receiptId: string;
    kind: import('./tool-call-receipts.js').ToolCallReceiptKeyKind;
    digest: string;
  };
  approvals: {
    id: string;
    status: string;
    expiresAt: Date;
    taskId: string;
    resolvedAt: Date | null;
    summary: string;
    toolCallId: string;
    shortCode: string;
    payload: unknown;
    resolutionPayload: unknown;
    requestedAt: Date;
    resolvedVia: string | null;
    notifiedChannels: string[];
    createdPolicyId: string | null;
  };
  applicationConfirmations: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    expiresAt: Date;
    lastError: string | null;
    conversationId: string | null;
    role: string;
    sourceTaskId: string;
    company: string;
    expectedSenderEmails: string[];
    confirmationTokenHash: string;
    confirmationTokenHint: string;
    trackerUpdate: unknown;
    documentUpdate: unknown;
    actionState: unknown;
    confirmationMessageId: string | null;
    confirmationFrom: string | null;
    confirmedAt: Date | null;
    /** Owner privacy generation captured when its internal application task was committed. */
    producerPrivacyGeneration: string | null;
  };
  approvalPolicies: {
    id: string;
    match: unknown;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    version: number;
    enabled: boolean;
    toolName: string;
    templateKey: string;
    effect: string;
    createdVia: string;
  };
  anomalies: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    kind: string;
    toolName: string;
    policyId: string | null;
    observed: number;
    expected: number;
    toolCallIds: string[];
    detail: string;
    windowLabel: string;
    subjectKey: string;
  };
  assistantHealthAlerts: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    kind: string;
    detail: string;
    observationCount: number;
    firstSeenAt: Date;
    lastSeenAt: Date;
    lastNotifiedAt: Date | null;
  };
  skills: {
    id: string;
    name: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    embedding: number[] | null;
    embeddingSpaceKey: string | null;
    sourceTaskId: string | null;
    preconditions: string;
    steps: string;
    gotchas: string;
    originTrust: string;
    ownerAuthored: boolean;
    useCount: number;
    successCount: number;
    failureCount: number;
    lastVerifiedAt: Date | null;
    deprecated: boolean;
  };
  skillLibraryRevisions: {
    agentId: string;
    revision: number;
    updatedAt: Date;
  };
  improvementProposals: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    title: string;
    status: string;
    kind: string;
    rationale: string;
    change: unknown;
    evidenceIds: string[];
  };
  memories: {
    id: string;
    createdAt: Date;
    agentId: string;
    expiresAt: Date | null;
    embedding: number[] | null;
    sourceTaskId: string | null;
    kind: string;
    confidence: string;
    contentHash: string;
    goalId: string | null;
    originTrust: string;
    category: string;
    content: string;
    importance: number;
    quarantined: boolean;
    subjectContactId: string | null;
    domain: string | null;
    validFrom: Date | null;
    validUntil: Date | null;
    supersededById: string | null;
    ownerConfirmed: boolean;
    pinned: boolean;
    source: string | null;
    /** Exact provider/model/width revision used for this stored vector; null is unknown. */
    embeddingSpaceKey: string | null;
    lastAccessedAt: Date | null;
    lastConsolidatedAt: Date | null;
  };
  memoryEmbeddingRefreshes: {
    id: string;
    agentId: string;
    memoryId: string;
    sourceHash: string;
    targetSpaceKey: string;
    targetDimensions: number;
    observedSpaceKey: string | null;
    status: string;
    preparedVector: number[] | null;
    privacyGeneration: string | null;
    claimToken: string | null;
    leaseUntil: Date | null;
    unknownReason: string | null;
    createdAt: Date;
    updatedAt: Date;
  };
  memoryTombstones: { id: string; createdAt: Date; contentHash: string; reason: string };
  ownerCard: { id: number; content: string; compiledAt: Date };
  contacts: {
    id: string;
    name: string;
    createdAt: Date;
    updatedAt: Date;
    trust: string;
    aliases: string[];
    emails: string[];
    phones: string[];
    relationship: string;
    notes: string;
  };
  knowledgeGraphEntities: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    kind: string;
    canonicalKey: string;
    label: string;
    preferredLabel: string | null;
    contactId: string | null;
  };
  knowledgeGraphEntityAliases: {
    id: string;
    createdAt: Date;
    agentId: string;
    canonicalKey: string;
    entityId: string;
  };
  knowledgeGraphSources: {
    createdAt: Date;
    updatedAt: Date;
    status: string;
    lastError: string | null;
    contentHash: string;
    subjectContactId: string | null;
    memoryId: string;
    extractionVersion: number;
    nextRetryAt: Date | null;
    attempts: number;
  };
  knowledgeGraphRelations: {
    id: string;
    createdAt: Date;
    agentId: string;
    sourceFingerprint: string;
    confidence: string;
    validFrom: string | null;
    validUntil: string | null;
    subjectEntityId: string;
    predicate: string;
    assertion: KnowledgeGraphAssertion;
    assertionId: string | null;
    objectEntityId: string;
    sourceMemoryId: string;
    evidenceQuote: string | null;
    ordinal: number;
    reviewStatus: string;
    reviewedAt: Date | null;
    correctedByRelationId: string | null;
    correctionSourceContentHash: string | null;
    correctionDisposition: string | null;
  };
  knowledgeGraphAssertions: {
    id: string;
    agentId: string;
    semanticKey: string;
    subjectEntityId: string;
    predicate: string;
    objectEntityId: string;
    assertion: KnowledgeGraphAssertion;
    qualifiers: Record<string, string | number | boolean | null>;
    validFrom: string | null;
    validUntil: string | null;
    semanticRevision: number;
    evidenceRevision: number;
    lifecycle: string;
    reviewStatus: string;
    reviewedRevision: number | null;
    reviewedPayloadHash: string | null;
    ownerAuthored: boolean;
    supersededById: string | null;
    createdAt: Date;
    updatedAt: Date;
  };
  knowledgeGraphAssertionEvidence: {
    id: string;
    agentId: string;
    assertionId: string;
    sourceMemoryId: string;
    sourceFingerprint: string;
    sourceContentHash: string;
    evidenceQuote: string;
    sourceAuthor: string;
    sourceTrust: string;
    independent: boolean;
    spanStart: number | null;
    spanEnd: number | null;
    extractionVersion: number;
    evidenceRevision: number;
    observedAt: Date;
    createdAt: Date;
  };
  occasions: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    kind: string;
    originTrust: string;
    quarantined: boolean;
    notes: string;
    ownerConfirmed: boolean;
    source: string | null;
    label: string;
    contactId: string;
    month: number;
    day: number;
    year: number | null;
    recurrence: string;
    leadDays: number;
  };
  importSources: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    taskId: string | null;
    kind: string;
    error: string | null;
    source: string;
    workspacePath: string;
    itemsTotal: number | null;
    itemsProcessed: number;
    memoriesSaved: number;
    memoriesQuarantined: number;
    parseDiagnostics: import('./import-jobs.js').ImportArchiveDiagnostics | null;
  };
  memoryImportLineage: {
    source: string;
    memoryId: string;
    sourceUnitProvenance: import('./import-jobs.js').ImportUnitProvenance[];
    createdAt: Date;
  };
  occasionImportLineage: {
    source: string;
    occasionId: string;
    createdAt: Date;
  };
  models: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    enabled: boolean;
    label: string;
    capabilities: unknown;
    promptCostPerMTok: string | null;
    completionCostPerMTok: string | null;
    latencyClass: string;
  };
  /** An owner-connected model provider. The API key is sealed; never expose it. */
  modelConnections: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    kind: string;
    label: string;
    baseUrl: string | null;
    apiKeyEncrypted: string | null;
    vertexProject: string | null;
    vertexLocation: string | null;
    enabled: boolean;
    lastTestedAt: Date | null;
    lastError: string | null;
  };
  modelRoles: {
    updatedAt: Date;
    role: string;
    primaryModel: string;
    fallbackModel: string;
    params: unknown;
  };
  modelRoleRevisions: {
    id: string;
    role: string;
    beforeState: unknown | null;
    afterState: unknown | null;
    source: string;
    baselineKnown: boolean;
    requiresOwnerReview: boolean;
    createdAt: Date;
  };
  modelCalls: {
    id: string;
    createdAt: Date;
    taskId: string | null;
    role: string;
    model: string;
    inputTokens: number;
    outputTokens: number;
    costUsd: string;
    latencyMs: number | null;
    finishReason: string | null;
    openrouterGenerationId: string | null;
    runtimeRevision: string | null;
    runtimeReleaseSha: string | null;
  };
  /** What a model was asked and what it answered. Written only when capture is on. */
  modelCallAudit: {
    id: string;
    createdAt: Date;
    modelCallId: string | null;
    taskId: string | null;
    role: string;
    model: string;
    method: string;
    capture: string;
    systemPrompt: string | null;
    input: string | null;
    output: string | null;
    truncated: boolean;
    finishReason: string | null;
    latencyMs: number | null;
    inputTokens: number;
    outputTokens: number;
  };
  costEvents: {
    evidence: import('./cost-evidence.js').CostEvidence;
    id: string;
    createdAt: Date;
    description: string;
    taskId: string | null;
    toolCallId: string | null;
    source: string;
    quantity: string | null;
    unit: string | null;
    unitPriceUsd: string | null;
    usd: string;
    reservationId: string | null;
    idempotencyKey: string | null;
  };
  executionJobCallbackReceipts: {
    idempotencyKey: string;
    taskId: string;
    tokenHash: string;
    payloadDigest: string;
    queueGeneration: number;
    createdAt: Date;
  };
  costReservations: {
    id: string;
    createdAt: Date;
    status: string;
    description: string;
    taskId: string | null;
    source: string;
    estimatedUsd: string;
    actualUsd: string | null;
    reconciledAt: Date | null;
    attemptStartedAt: Date | null;
    attemptMetadata: unknown | null;
    unknownReason: string | null;
  };
  rateTable: { updatedAt: Date; unit: string; unitPriceUsd: string; key: string };
  budgets: {
    updatedAt: Date;
    scope: string;
    limitUsd: string;
    softPct: number;
    onSoft: string;
    onHard: string;
  };
  toolCache: { expiresAt: Date; toolName: string; result: unknown; cacheKey: string };
  rateLimits: {
    updatedAt: Date;
    scope: string;
    maxPerHour: number | null;
    maxPerDay: number | null;
  };
  writingSamples: {
    id: string;
    createdAt: Date;
    text: string;
    embedding: number[] | null;
    embeddingSpaceKey: string | null;
    register: string;
    context: string;
  };
  voiceProfile: {
    id: number;
    signature: string;
    updatedAt: Date;
    description: string;
    dos: unknown;
    donts: unknown;
  };
  gmailSyncState: {
    updatedAt: Date;
    mailbox: string;
    lastHistoryId: bigint | null;
    cursor: unknown;
    watchExpiration: Date | null;
    leaseHolder: string | null;
    leaseGeneration: number;
    leaseExpiresAt: Date | null;
  };
  emailIngest: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    conversationId: string | null;
    channelMessageId: string;
    category: string;
    importance: number;
    reason: string;
    fromEmail: string;
    fromName: string | null;
    subject: string;
    contentTrust: string;
    authenticated: boolean;
    ingestMode: string;
    hasExternalOrUnknown: boolean;
    observerRegistrySnapshot: Array<{ key: string; version: number; workClass: string }> | null;
    observerRegistryHash: string | null;
    admittedSourceKind: string | null;
    admittedSourceId: string | null;
    directRouting: 'application_confirmation' | 'email_triage' | 'needs_attention' | null;
    directRecoveryReason:
      | 'provider_message_missing'
      | 'provider_access_denied'
      | 'provider_temporarily_unavailable'
      | 'checkpoint_inconsistent'
      | null;
    emailContentProvenance: {
      version: 1;
      mode: 'direct' | 'forwarded';
      authenticated: boolean;
      sourceLength: number;
      storedLength: number;
      sourceHash: string;
      bodyHash: string;
      messageHash: string;
      prefixLength: number;
      hasExternalOrUnknown: boolean;
      spans: Array<{ start: number; end: number; author: 'sender' | 'external' | 'unknown' }>;
      parts: Array<{
        path: string;
        mimeType: string;
        quoteMarkup: boolean;
        replyHeaders: boolean;
        bodyQuoteStart?: number;
      }>;
    } | null;
    classificationStatus: string;
    classificationClaimToken: string | null;
    preparedClassification: { automated: boolean } | null;
    scoreOutcome: string;
    actionable: boolean;
    dates: unknown;
    mailbox: string;
    providerMessageId: string | null;
    sourceMessageId: string | null;
    providerThreadId: string | null;
    providerReceivedAt: Date | null;
    securityEvidence: {
      providerIncidentRef?: string;
      eventType?: string;
      affectedAccount?: string;
      eventAt?: string;
      device?: string;
      location?: string;
      recoveryCopyOf?: string;
      evidenceQuote?: string;
    } | null;
    securityIncidentId: string | null;
    obligationStatus: string;
    obligationVersion: number;
    obligationDecision: string | null;
    obligationDecisionAt: Date | null;
    obligationSnoozedUntil: Date | null;
    pipelineStage: string;
    scoreStatus: string;
    scoreClaimToken: string | null;
    cardCandidate: boolean;
    nextStep: string | null;
    messagePersisted: boolean;
    triageTaskId: string | null;
    triaged: boolean;
    extractedAt: Date | null;
    preparedExtraction: unknown | null;
  };
  emailObserverSources: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    sourceKey: string;
    channelMessageId: string;
    body: string;
    privacyGeneration: string | null;
  };
  emailObserverWork: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    sourceKey: string;
    channelMessageId: string;
    sourceKind: 'message' | 'automated_source';
    observerKey: string;
    observerVersion: number;
    workClass: 'idempotent_db' | 'paid_ambiguous' | 'external_provider';
    status:
      | 'pending'
      | 'claimed'
      | 'prepared'
      | 'complete'
      | 'no_op'
      | 'retryable_failed'
      | 'unknown'
      | 'skipped_erased'
      | 'skipped_budget';
    attemptCount: number;
    claimToken: string | null;
    claimGeneration: number;
    leaseExpiresAt: Date | null;
    privacyGeneration: string | null;
    budgetKey: string | null;
    budgetWindowStart: Date | null;
    budgetReserved: boolean;
    preparedResult: unknown | null;
    deliveryKey: string | null;
    lastErrorCode: string | null;
    claimedAt: Date | null;
    completedAt: Date | null;
  };
  emailObserverBudgets: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    observerKey: string;
    utcWindowStart: Date;
    utcWindowEnd: Date;
    reservedCount: number;
    limit: number;
  };
  emailBookingOccurrences: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    bookingKey: string;
    lifecycle: string;
    dates: unknown;
    sourceChannelMessageId: string;
    sourceReceivedAt: Date;
    sourceAuthenticated: boolean;
    version: number;
  };
  securityIncidents: {
    id: string;
    agentId: string;
    incidentKey: string;
    confidence: string;
    revision: number;
    disposition: string;
    decisionRevision: number | null;
    decisionReason: string | null;
    materialChangeReason: string | null;
    createdAt: Date;
    updatedAt: Date;
  };
  securityIncidentSources: {
    id: string;
    agentId: string;
    incidentId: string;
    channelMessageId: string;
    sourceMessageId: string | null;
    mailboxHash: string;
    evidenceFingerprint: string;
    observedAt: Date;
    createdAt: Date;
  };
  securityIncidentAttention: {
    id: string;
    agentId: string;
    incidentId: string;
    revision: number;
    producer: string;
    deliveryStatus: string;
    createdAt: Date;
    updatedAt: Date;
  };
  suggestions: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    expiresAt: Date;
    conversationId: string | null;
    origin: string;
    bookingKey: string | null;
    bookingVersion: number | null;
    bookingCancellation: { calendarEventId: string; bookingIdentity: string } | null;
    snoozedUntil: Date | null;
    summary: string;
    proposedAction: string;
    sourceRef: string;
    acceptedTaskId: string | null;
  };
  schedules: {
    id: string;
    name: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    enabled: boolean;
    cron: string;
    taskTemplate: unknown;
    seedTemplateKey: string | null;
    seedTemplateRevision: number | null;
    seedDefinition: unknown | null;
    seedReviewRequired: boolean;
    lastRunAt: Date | null;
    nextRunAt: Date | null;
  };
  watches: {
    id: string;
    name: string;
    match: unknown;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    expiresAt: Date;
    conversationId: string | null;
    kind: string;
    state: unknown;
    tier: string;
    fireCount: number;
    maxFires: number | null;
    lastFiredAt: Date | null;
    nextPollAt: Date | null;
    pollIntervalSeconds: number | null;
  };
  watchFires: {
    id: string;
    createdAt: Date;
    agentId: string;
    summary: string;
    watchId: string;
    triggerRef: string;
    excerpt: string;
  };
  watchFireEffects: {
    id: string;
    agentId: string;
    watchId: string;
    fireId: string;
    kind: string;
    status: string;
    idempotencyKey: string;
    payload: unknown;
    attempts: number;
    claimedAt: Date | null;
    leaseUntil: Date | null;
    result: unknown;
    createdAt: Date;
    updatedAt: Date;
  };
  notificationPrefs: {
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    quietStartMin: number | null;
    quietEndMin: number | null;
    ambientDailyCap: number | null;
  };
  proactivePings: {
    id: string;
    createdAt: Date;
    agentId: string;
    channel: string;
    reason: string | null;
    urgency: string;
    delivered: boolean;
  };
  notificationOutbox: {
    id: string;
    agentId: string;
    deliveryKey: string;
    legKey: string;
    adapter: string;
    status: string;
    destination: unknown | null;
    payload: unknown | null;
    attempts: number;
    retryable: boolean;
    availableAt: Date;
    leaseToken: string | null;
    leaseUntil: Date | null;
    providerMessageId: string | null;
    result: unknown;
    /** Non-secret producer association; never persist the observer claim token. */
    producerWorkId?: string | null;
    producerTaskId?: string | null;
    producerApplicationId?: string | null;
    producerConfirmationMessageId?: string | null;
    producerPrivacyGeneration?: string | null;
    finishedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
  };
  proactiveMoments: {
    id: string;
    agentId: string;
    kind: string;
    summary: string;
    momentKey: string;
    pinged: boolean;
    deliveredAt: Date;
  };
  calendarEventSnapshots: {
    id: string;
    agentId: string;
    calendarId: string;
    eventId: string;
    iCalUID: string | null;
    summary: string;
    start: string;
    end: string;
    status: string | null;
    attendeeResponseHash: unknown;
    updatedAt: Date;
  };
  canaryRuns: {
    id: string;
    status: string;
    startedAt: Date;
    error: string | null;
    finishedAt: Date | null;
    ok: boolean | null;
    checks: unknown;
    browserCallbackTokenHash: string | null;
    browserResult: unknown;
  };
  emailAttachmentCustodies: {
    id: string;
    agentId: string;
    observerWorkId: string | null;
    claimToken: string | null;
    claimGeneration: number;
    privacyGeneration: string | null;
    channelMessageId: string | null;
    providerMessageId: string | null;
    providerAttachmentId: string | null;
    manifestDigest: string | null;
    attachmentOrdinal: number;
    workspacePath: string;
    filename: string | null;
    mime: string | null;
    advertisedBytes: number;
    actualBytes: number | null;
    sha256: string | null;
    markerGeneration: string | null;
    objectGeneration: string | null;
    status: string;
    fileId: string | null;
    documentId: string | null;
    duplicateDocumentId: string | null;
    leaseExpiresAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
  };
  files: {
    id: string;
    createdAt: Date;
    agentId: string;
    taskId: string | null;
    workspacePath: string;
    mime: string;
    bytes: number;
    sha256: string | null;
    objectGeneration: string | null;
    emailAttachmentCustodyId: string | null;
  };
  documents: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    title: string;
    status: string;
    trust: string;
    error: string | null;
    source: string;
    sourceRef: string;
    mime: string;
    sha256: string;
    fileId: string;
    extractor: string;
    chunkCount: number;
    charCount: number;
    processorTokenHash: string | null;
    processorStartedAt: Date | null;
    processorAttempts: number;
    processedTextPath: string | null;
    extractionMetadata: DocumentExtractionMetadata | null;
  };
  documentChunks: {
    id: string;
    createdAt: Date;
    agentId: string;
    text: string;
    embedding: number[] | null;
    embeddingSpaceKey: string | null;
    charCount: number;
    documentId: string;
    chunkIndex: number;
  };
  locationPings: {
    id: string;
    createdAt: Date;
    agentId: string;
    source: string;
    label: string;
    lat: string;
    lng: string;
    accuracyM: number | null;
    timeZone: string | null;
    capturedAt: Date;
    arrivalExpiresAt: Date | null;
  };
  ambientSnapshots: {
    id: string;
    agentId: string;
    block: string;
    flags: unknown;
    sources: unknown;
    computedAt: Date;
  };
  dreamNotes: {
    id: string;
    createdAt: Date;
    agentId: string;
    expiresAt: Date;
    kind: string;
    content: string;
    refIds: string[];
  };
  deviceTokens: {
    id: string;
    createdAt: Date;
    agentId: string;
    lastSeenAt: Date;
    token: string;
    platform: string;
    environment: string;
    invalidatedAt: Date | null;
  };
  selfMaintenance: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    title: string;
    status: string;
    proposalId: string | null;
    diagnosis: string;
    targetArea: string;
    blockedReason: string | null;
    prNumber: number | null;
    prUrl: string | null;
  };
  responseChecks: {
    id: string;
    createdAt: Date;
    taskId: string;
    promptVersion: number;
    plannerVersion: number | null;
    blocked: boolean;
    unsupportedCount: number;
    mustActRetries: number;
    degradedSteps: number;
    outputVerificationAttempted: boolean;
    outputVerificationRevised: boolean;
    outputVerificationUnavailable: boolean;
  };
  recallMetrics: {
    id: string;
    createdAt: Date;
    agentId: string;
    conversationId: string | null;
    taskId: string | null;
    path: string;
    graphAttempted: boolean;
    graphFailed: boolean;
    historyFailed: boolean;
    graphCandidates: number;
    graphUsed: number;
    historyTier: string;
    historyUsed: number;
    sourceCount: number;
  };
  recallFeedback: {
    id: string;
    createdAt: Date;
    agentId: string;
    messageId: string;
    sourceCount: number;
    verdict: string;
  };
  /** Content-free owner history of source identities disclosed by assistant replies. */
  recallSurfaces: {
    id: string;
    agentId: string;
    sourceKey: string;
    sourceRevision: string | null;
    kind: string;
    firstSurfacedAt: Date;
    lastSurfacedAt: Date;
    lastMessageId: string | null;
    surfaceCount: number;
    suppressedAt: Date | null;
    version: number;
  };
}
export type RecordOf<K extends keyof Records> = Records[K];
